export const INFO_SETTINGS_FORM_NAME = 'settings';
export const INFO_SETTINGS_FORM_CHILD_NAME_INPUT_MIN = 3;
export const INFO_SETTINGS_FORM_CHILD_NAME_INPUT_MAX = 32;
export const INFO_SETTINGS_IMAGE_MAX_SIZE = 1024 * 500;
