export const FETCH_INOCULATIONS_ENTRIES = 'FETCH_INOCULATIONS_ENTRIES';
export const FETCH_INOCULATIONS_ENTRIES_SUCCESS = 'FETCH_INOCULATIONS_ENTRIES_SUCCESS';
export const FETCH_INOCULATIONS_ENTRIES_FAILURE = 'FETCH_INOCULATIONS_ENTRIES_FAILURE';
export const SUBMIT_INOCULATIONS_FORM = 'SUBMIT_INOCULATIONS_FORM';
export const SUBMIT_INOCULATIONS_FORM_SUCCESS = 'SUBMIT_INOCULATIONS_FORM_SUCCESS';
export const SUBMIT_INOCULATIONS_FORM_FAILURE = 'SUBMIT_INOCULATIONS_FORM_FAILURE';
