export const FETCH_INOCULATIONS_ENTRIES = 'FETCH_INOCULATIONS_ENTRIES';
export const FETCH_INOCULATIONS_ENTRIES_SUCCESS = 'FETCH_INOCULATIONS_ENTRIES_SUCCESS';
export const FETCH_INOCULATIONS_ENTRIES_FAILURE = 'FETCH_INOCULATIONS_ENTRIES_FAILURE';
