export const FETCH_NOTES_ENTRIES = 'FETCH_NOTES_ENTRIES';
export const FETCH_NOTES_ENTRIES_SUCCESS = 'FETCH_NOTES_ENTRIES_SUCCESS';
export const FETCH_NOTES_ENTRIES_FAILURE = 'FETCH_NOTES_ENTRIES_FAILURE';
export const SUBMIT_NOTES_FORM = 'SUBMIT_NOTES_FORM';
export const SUBMIT_NOTES_FORM_SUCCESS = 'SUBMIT_NOTES_FORM_SUCCESS';
export const SUBMIT_NOTES_FORM_FAILURE = 'SUBMIT_NOTES_FORM_FAILURE';
